### ISSUE TITLE
Update polygons data based on public dataset

### ISSUE THREAD

**Issue by NairolfL** [whosonfirst-data/whosonfirst-data-admin-lu#13]
Hello,
I'd like to take some time to update this repository with data from https://data.public.lu/en/datasets/limites-administratives-du-grand-duche-de-luxembourg/#_

It contains up to date and precise polygons for most localities in Luxembourg.
For example, Esch sur Alzette : https://github.com/whosonfirst-data/whosonfirst-data-admin-lu/blob/master/data/101/839/803/101839803.geojson should look like this according to data.public.lu : 
![Screenshot from 2021-04-27 11-59-36](https://user-images.githubusercontent.com/3017151/116223754-27176900-a750-11eb-8030-7f5088c4f136.png)

while looking like this on the current whosonfirst data : 
![Screenshot from 2021-04-27 12-00-04](https://user-images.githubusercontent.com/3017151/116223816-35fe1b80-a750-11eb-9382-09c9045f1dc0.png)

Would you accept a merge request if I take some time to write a script and update it ?

**Comment by stepps00** [comment]
Hi @NairolfL - thanks for filing the issue.

When updating records in Who's On First, there are various steps to take. In Who's On First, existiing geometries are stored as "[alt geometries](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md)", so we can't simply overwrite what exists.

As a first step, would you be able to provide us a mapping of each Who's On First localadmin `wof:id` to the source file's commune `LAU2` code?

There are 102 communes in the source file and 107 localadmin in Who's On First, so mapping those (and figuring out what to do with the diff of 5) would be a great start.

Also, it looks like the data is in the Public Domain, which is great. This license works with Who's On First's [license](https://www.whosonfirst.org/docs/licenses/).

**Comment by NairolfL** [comment]
Hello,
I linked the LAU2 code to wof:id : 
| Name                 | LAU2 | wofid      | Comment                                                                                                                            |
|----------------------|------|------------|------------------------------------------------------------------------------------------------------------------------------------|
| Beaufort             | 1001 | 1125402081 |                                                                                                                                    |
| Bech                 | 1002 | 1125328045 |                                                                                                                                    |
| Beckerich            | 0701 | 1125325865 |                                                                                                                                    |
| Berdorf              | 1003 | 1125350967 |                                                                                                                                    |
| Bertrange            | 0301 | 1125366337 |                                                                                                                                    |
| Bettembourg          | 0201 | 1125357423 |                                                                                                                                    |
| Bettendorf           | 0601 | 1125351511 |                                                                                                                                    |
| Betzdorf             | 1101 | 1125325873 |                                                                                                                                    |
| Bissen               | 0402 | 1125303385 |                                                                                                                                    |
| Biwer                | 1102 | 1125294519 |                                                                                                                                    |
| Boulaide             | 0801 | 1125366297 |                                                                                                                                    |
| Bourscheid           | 0602 | 1125333097 |                                                                                                                                    |
| Bous                 | 1201 | 1125294523 |                                                                                                                                    |
| Clervaux             | 0501 | 1125411213 |                                                                                                                                    |
| Colmar-Berg          | 0401 | 1125350981 | Named Berg in WOF data                                                                                                             |
| Consdorf             | 1004 | 1125285639 |                                                                                                                                    |
| Contern              | 0302 | 101812909  | Is a locality in WOF data not localadmin                                                                                           |
| Dalheim              | 1202 | 1125283997 |                                                                                                                                    |
| Diekirch             | 0603 | 1125390659 |                                                                                                                                    |
| Differdange          | 0202 | 1125280445 |                                                                                                                                    |
| Dippach              | 0101 | 1125285649 |                                                                                                                                    |
| Dudelange            | 0203 | 1125357415 |                                                                                                                                    |
| Echternach           | 1005 | 1125303769 |                                                                                                                                    |
| Ell                  | 0703 | 1125306051 |                                                                                                                                    |
| Erpeldange-sur-Sûre  | 0604 | 1125386695 |                                                                                                                                    |
| Esch-sur-Alzette     | 0204 | 1125366319 |                                                                                                                                    |
| Esch-sur-Sûre        | 0802 | 1125333105 |                                                                                                                                    |
| Ettelbruck           | 0605 | 1125311519 |                                                                                                                                    |
| Feulen               | 0606 | 1125284603 |                                                                                                                                    |
| Fischbach            | 0404 | 1125305509 |                                                                                                                                    |
| Flaxweiler           | 1103 | 1125284029 |                                                                                                                                    |
| Frisange             | 0205 | 1125410585 |                                                                                                                                    |
| Garnich              | 0102 | 1125284663 |                                                                                                                                    |
| Goesdorf             | 0804 | 1125298213 |                                                                                                                                    |
| Grevenmacher         | 1104 | 1125415535 |                                                                                                                                    |
| Grosbous             | 0705 | 1125284431 |                                                                                                                                    |
| Habscht              | 0103 | 1125284213 |                                                                                                                                    |
| Heffingen            | 0405 | 1125288903 |                                                                                                                                    |
| Helperknapp          | 0403 |            | https://fr.wikipedia.org/wiki/Helperknapp merged from 1125410763 AND 1125366369                                                    |
| Hesperange           | 0303 | 1125305925 |                                                                                                                                    |
| Junglinster          | 1105 | 1125296455 |                                                                                                                                    |
| Kayl                 | 0206 | 1125407267 |                                                                                                                                    |
| Kehlen               | 0105 | 1125376161 |                                                                                                                                    |
| Kiischpelt           | 0805 | 1125312135 | Named Kischpelt in WOF data                                                                                                        |
| Koerich              | 0106 | 1125366349 |                                                                                                                                    |
| Kopstal              | 0107 | 1125286175 |                                                                                                                                    |
| Käerjeng             | 0104 |            | https://fr.wikipedia.org/wiki/K%C3%A4erjeng#Sections_de_la_commune merge of 1125284565 1125415609 1125765939 1125781115 1125781203 |
| Lac de la Haute Sûre | 0806 | 1125283425 |                                                                                                                                    |
| Larochette           | 0406 | 1125402083 |                                                                                                                                    |
| Lenningen            | 1203 | 1125325879 |                                                                                                                                    |
| Leudelange           | 0207 | 1125396325 |                                                                                                                                    |
| Lintgen              | 0407 | 1125288915 |                                                                                                                                    |
| Lorentzweiler        | 0408 | 1125366377 |                                                                                                                                    |
| Luxembourg           | 0304 | 1125286201 |                                                                                                                                    |
| Mamer                | 0108 | 1125305791 |                                                                                                                                    |
| Manternach           | 1106 | 1125305331 |                                                                                                                                    |
| Mersch               | 0409 | 1125286143 |                                                                                                                                    |
| Mertert              | 1107 | 1125366357 | is_current = -1 means disabled ? shouldn't be                                                                                      |
| Mertzig              | 0607 | 1125305933 |                                                                                                                                    |
| Mondercange          | 0208 | 1125293961 |                                                                                                                                    |
| Mondorf-les-Bains    | 1204 | 1125366329 |                                                                                                                                    |
| Niederanven          | 0305 | 1125410759 |                                                                                                                                    |
| Nommern              | 0410 | 1125284735 |                                                                                                                                    |
| Parc Hosingen        | 0503 | 1125324097 | Named Hosingen in WOF data                                                                                                         |
| Préizerdaul          | 0702 | 1125352069 | https://fr.wikipedia.org/wiki/Pr%C3%A9izerdaul#Toponymie                                                                           |
| Putscheid            | 0902 | 1125410761 |                                                                                                                                    |
| Pétange              | 0209 | 1125283405 |                                                                                                                                    |
| Rambrouch            | 0704 | 1125410765 |                                                                                                                                    |
| Reckange-sur-Mess    | 0210 | 1125398375 | Wrong coordinates in WOF data                                                                                                      |
| Redange              | 0706 | 1125402395 | Named Redange-sur-Attert in WOF data                                                                                               |
| Reisdorf             | 0608 | 1125285897 |                                                                                                                                    |
| Remich               | 1205 | 1125327261 |                                                                                                                                    |
| Roeser               | 0211 | 1125324091 |                                                                                                                                    |
| Rosport-Mompach      | 1006 | 1125374547 | Named Mompach in WOF data                                                                                                          |
| Rumelange            | 0212 | 1125321401 |                                                                                                                                    |
| Saeul                | 0707 | 1126019793 | Is a locality in WOF data                                                                                                          |
| Sandweiler           | 0306 | 1125366287 |                                                                                                                                    |
| Sanem                | 0213 | 1125299915 |                                                                                                                                    |
| Schengen             | 1206 | 1125883515 | Is a locality in WOF data                                                                                                          |
| Schieren             | 0609 | 1126019305 | Is a locality in WOF data                                                                                                          |
| Schifflange          | 0214 | 1126015453 | Is a locality in WOF data                                                                                                          |
| Schuttrange          | 0307 | 1125375263 |                                                                                                                                    |
| Stadtbredimus        | 1207 | 1125341017 |                                                                                                                                    |
| Steinfort            | 0110 | 1125346159 |                                                                                                                                    |
| Steinsel             | 0308 | 1125305385 |                                                                                                                                    |
| Strassen             | 0309 | 1125320855 |                                                                                                                                    |
| Tandel               | 0901 | 1125952365 | Is a locality in WOF data                                                                                                          |
| Troisvierges         | 0504 | 1125352097 |                                                                                                                                    |
| Useldange            | 0708 | 1125366387 |                                                                                                                                    |
| Vallée de l'Ernz     | 0610 | 1125283985 | https://fr.wikipedia.org/wiki/Vall%C3%A9e_de_l%27Ernz Merge of Ermsdorf with others                                                |
| Vianden              | 0903 | 1125303779 |                                                                                                                                    |
| Vichten              | 0709 | 1125958777 | Is a locality in WOF data                                                                                                          |
| Wahl                 | 0710 | 1125306043 |                                                                                                                                    |
| Waldbillig           | 1008 | 1125305359 |                                                                                                                                    |
| Waldbredimus         | 1208 | 1125288845 |                                                                                                                                    |
| Walferdange          | 0310 | 1125355305 |                                                                                                                                    |
| Weiler-la-Tour       | 0311 | 1125285789 |                                                                                                                                    |
| Weiswampach          | 0505 | 1125352025 |                                                                                                                                    |
| Wiltz                | 0807 | 1125390667 |                                                                                                                                    |
| Wincrange            | 0502 | 101811727  | Is a locality in WOF data                                                                                                          |
| Winseler             | 0808 | 1125284497 |                                                                                                                                    |
| Wormeldange          | 1108 | 1125311551 | is_current = -1 ? shouldn't be.                                                                                                     |

As you can see, there is a few without a wof:id, some with an existing id but linked to a locality.
Could you help me on what should this become ?
I added link to wikipedia pages when it's related to a merge of multiple communes and / or a renaming.
There is a few remaining in WOF data (with my comments on what we should do with it ): 
```
Attert,1125369433
    Attert is in Belgium.
    Confusing because this region of belgium is called Luxembourg. But it is a belgian region :
    https://en.wikipedia.org/wiki/Luxembourg_(Belgium)
Burmerange,1125351505
    I think this should be a locality, part of the Schengen localadmin
Gemeinde Echternacherbrück,1125349667
    This is in Germany
Eschweiler,1125366311
    I think this should be a locality, part of the Wiltz localadmin
Heiderscheid,1125297227
    I think this should be a locality, part of the Esch-sur-Sûre localadmin
Heinerscheid,1125398365
    I think this should be a locality, part of the Clervaux localadmin
Hoscheid,1125292863
    I think this should be a locality, part of the Parc Hosingen localadmin
Martelange,1125382829
    Martelange is in belgium. (in the luxembourg region of belgium)
Medernach,1125353993
    I think this should be a locality, part of the Vallée de l'Ernz localadmin
Munshausen,1125357351
    I think this should be a locality, part of the Clervaux localadmin
Neunhausen,1125410767
    I think this should be a locality, part of the Esch-sur-Sûre localadmin
Remerschen,1125311645
    I think this should be a locality, part of the Schengen localadmin
Septfontaines,1125274325
    I think this should be a locality, part of the Habscht localadmin
Wellenstein,1125305453
    I think this should be a locality, part of the Schengen localadmin
```

**Comment by NairolfL** [comment]
Hello @stepps00,
Did you have time to look at it ?
Could you help me to update the data ?

Thanks

**Comment by stepps00** [comment]
Hey @NairolfL thanks for the nudge.. unfortunately I have not had time to review this yet, but I will devote time to it soon and reply here. This type of update typically takes over a week to complete in total, so I'll come up with a plan to import these ASAP.

**Comment by stepps00** [comment]
Hi @NairolfL I've created a new issue in main `whosonfirst-data` repo (linked above) to track admin updates in Luxembourg. I'll close this issue.
